units:
  kx: U
  ky: U
  px: U+1
  py: U+1
  mcux: 18
  mcuy: 36
  jacky: 6
  jackx: 14
points:
  zones:
    matrix:
      key:
        padding: px
        spread: px
      anchor:
        shift: [150, -150]
      columns:
        outer:
          key.column_net: P4
        pinky:
          key.splay: -3
          key.column_net: P5
        ring:
          key.splay: -3
          key.stagger: 3
          key.column_net: P6
        middle:
          key.splay: -4
          key.stagger: 5
          rows.mod.skip: true
          key.column_net: P7
        index:
          key.stagger: -5
          key.splay: -3
          rows.mod.skip: true
          key.column_net: P8
        inner:
          key.stagger: -6
          rows.mod.skip: true
          key.column_net: P9
    
      rows:
        mod:
          row_net: P10
        bottom:
          row_net: P16
        home:
          row_net: P14
        top:
          row_net: P15
        num:
          row_net: P18
    thumbs:
      anchor:
        shift: [150, -148]
      columns:
        layer:
          key.column_net: P8
          key.splay: -15
        space:
          key.column_net: P9
      rows:
        cluster:
          shift: [5ky,0.5ky]
          row_net: P10
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx,ky]
  keys:
      - what: rectangle
        where: true
        size: [kx-0.5, ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_num
          shift: [-0.6px,0.6py]
        - ref: matrix_ring_num
          shift: [-0.6px,0.6py]
        - ref: matrix_middle_num
          shift: [0px,0.7py]
        - ref: matrix_index_num
          shift: [0.6px,0.6py]
        - ref: matrix_inner_num
          shift: [2px,0.5py]

        - ref: thumbs_space_cluster
          shift: [1px,-0.6py]



        - ref: matrix_outer_mod
          shift: [-0.6px,-0.6py]
      fillet: 2
  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  kbd:
    outlines:
      main:
        outline: board
    footprints:
      keys: 
        what: switch_mx
        where:
          - /matrix/
          - /thumbs/
        params:
          include_keycap: true
          hotswap_pads_same_side: true
          include_traces_vias: true
          reversible: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      mcu:
        what: mcu_supermini_nrf52840
        params:
          # orientation: "down"
          # reversable_pins: 13
          reversible: true
          reverse_mount: false
          show_instructions: false
        where:
          - ref: matrix_inner_num
            # te 2.5 bo ten footprint dodaje napis nad MCU
            shift: [mcux + 0.25px, -0.5py] 
            # rotate: -90
      reset: 
        what: wuerth-434121025816 
        params:
          r1: RST
          r2: GND
        where:
          ref: matrix_inner_home
          shift: [1.25px,0.3py]
      jack: 
        what: trrs_pj320a
        params:
          reversible: true
          symmetric: true
          TP: VCC
          R1: ""
          R2: P0
          SL: GND
        where:
          ref: matrix_inner_home
          shift: [1.5px,-0.25py]
          rotate: -90
      diode:
        what: diode_tht_sod123
        where: true
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      diode-key-route:
        what: utility_router
        where: true
        params:
          route: "f(-5.842 -5.08) (-6.5 -4) (-6.5 2) (-6 2.5) (1.2 2.5) (1.7 3) (1.7 5) b(1.7 3) (1.2 2.5) (-6 2.5) (-6.5 2) (-6.5 -2)"

      mhole_middle_down:
        what: mounting_hole_plated
        where:
          ref.aggregate.parts:
            - matrix_ring_home
            - matrix_middle_home
          shift: [0.5ky,-3ky]

      mhole_right_down:
        what: mounting_hole_plated
        where:
          ref: thumbs_space_cluster
          shift: [0.75kx, -0.45kx]
      mhole_left_down:
        what: mounting_hole_plated
        where:
          ref: matrix_outer_mod
          shift: [-0.5kx, -0.5kx]
      mhole_left_up:
        what: mounting_hole_plated
        where:
          ref: matrix_outer_num
          shift: [0.65kx, 0.5kx]
      mhole_middle_up:
        what: mounting_hole_plated
        where:
          ref: matrix_ring_num
          shift: [0.65kx, 0.6kx]
      mhole_right_up:
        what: mounting_hole_plated
        where:
          ref: matrix_inner_num
          shift: [0.65kx, 0.6kx]
      mhole_middle_middle_right:
        what: mounting_hole_plated
        where:
          ref: matrix_middle_home
          shift: [0.6kx,0.25py]
      mhole_middle_middle_left:
        what: mounting_hole_plated
        where:
          ref: matrix_pinky_home
          shift: [0.6kx,0.5py]
